In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

In [2]:
H = np.array([[1,2,-1],[1,0,1],[4,-4,5]])
print(H)

[[ 1  2 -1]
 [ 1  0  1]
 [ 4 -4  5]]


In [3]:
def norma(v):
  N = len(v)
  contador = 0
  for i in range(N):
    contador += v[i]**2
  contador = np.sqrt(contador)
  return contador


In [4]:
def algoritmoDePotenciaInversa(A,itmax=10000,mu=1.00001):
  N = len(A)
  v_0 = np.array([0,0,1])
  v_0 = v_0/np.linalg.norm(v_0)  

  A_inversa = np.linalg.inv(A- mu * np.identity(A.shape[0]))
  for it in range(itmax):
    
    v_1 = A_inversa @ v_0
    v_1 = v_1/np.linalg.norm(v_1)
    lambda_min = np.dot(v_1,np.dot(A,v_1))
    norma_0 = np.linalg.norm(v_0)
    norma_1 = np.linalg.norm(v_1)
    if abs(norma_0 - norma_1) <= 1E-5:
      break
    v_0 = v_1
  
  return lambda_min,-v_1
    
    
  

In [5]:
lambda_min,vector1 = algoritmoDePotenciaInversa(H)
print(round(lambda_min,5))
print(vector1)


1.00002
[ 0.40824693 -0.40824693 -0.81649794]


In [6]:
np.linalg.eig(H)[0]


array([3., 2., 1.])

In [7]:
np.linalg.eig(H)[1]

array([[-0.23570226,  0.43643578,  0.40824829],
       [ 0.23570226, -0.21821789, -0.40824829],
       [ 0.94280904, -0.87287156, -0.81649658]])