In [ ]:
import numpy as np

In [ ]:
def rotation_matrix(theta,i,j):
 R = np.zeros((3,3))
 if (i,j) == (1,0) or (i,j) == (0,1):
  R[0][0] = round(np.cos(theta),15)
  R[1][1] = round(np.cos(theta),15)
  R[0][1] = round(np.sin(theta),15)
  R[1][0] = round(-1*np.sin(theta),15)
  R[2][2] = 1
 elif (i,j) == (2,0) or (i,j) == (0,2):
  R[0][0] = round(np.cos(theta),15)
  R[2][2] = round(np.cos(theta),15)
  R[0][2] = round(np.sin(theta),15)
  R[2][0] = round(-1*np.sin(theta),15)
  R[1][1] = 1
 elif (i,j) == (2,1) or (i,j) == (1,2):
  R[2][2] = round(np.cos(theta),15)
  R[1][1] = round(np.cos(theta),15)
  R[1][2] = round(np.sin(theta),15)
  R[2][1] = round(-1*np.sin(theta),15)
  R[0][0] = 1

 return R



In [ ]:
 print(rotation_matrix(1,2,0))
 A = rotation_matrix(1,2,0)

[[ 0.54030231  0.          0.84147098]
 [ 0.          1.          0.        ]
 [-0.84147098  0.          0.54030231]]


In [ ]:
def inverse(A):
  N = len(A)
  B = np.zeros((N,N))
  for i in range(N):
    for j in range(N):
      B[j][i] = A[i][j]
  return B


In [ ]:
print(inverse(A))

[[ 0.54030231  0.         -0.84147098]
 [ 0.          1.          0.        ]
 [ 0.84147098  0.          0.54030231]]


In [ ]:
def jacobi_diagonalization(A,itmax=1000):
  N = len(A)
  A_copy = A.copy()
  for it in range(itmax):
    contador = 0
    dominante = 0
    for i in range(N):
      for j in range(N):
        if i != j:
          if A[i][j] > dominante:
            dominante = A[i][j]
            I,J = i,j
    for i in range(N):
      for j in range(N):
        if i != j: 
          if A[i][j] == 0:
            contador +=1
    if contador == 6:
      break
    if A[I][I] == A[J][J]:
      theta = np.pi/4
    else: 
      theta = (1/2)*np.arctan((2*A[I][J])/(A[I][I]-A[J][J]))
    R = rotation_matrix(theta,I,J)
    R_1 = inverse(R)
    pre_matrix = np.matmul(A,R)
    A = np.matmul(R_1,pre_matrix)
  B = np.zeros(3)
  for i in range(N):
    for j in range(N):
      if i == j:
        B[i] = A[i][i]


    


  return B

In [ ]:
simetrica = np.array([[4,1,1],[1,3,2],[1,2,5]])

In [ ]:
jacobi_diagonalization(simetrica)

array([6.89484249, 3.3975584 , 1.70759911])

In [ ]:
np.linalg.eig(simetrica)[0]

array([6.89510652, 3.39729507, 1.70759841])