In [1]:
import numpy as np

In [2]:
D0 = np.diag([1, 1, -1, -1])
D1 = np.fliplr(D0)
D2 = np.fliplr(np.diag([-1j, 1j, 1j, -1j]))
D3 = np.array([[0,0,1,0],[0,0,0,-1],[-1,0,0,0],[0,1,0,0]])

D = np.array([D0,D1,D2,D3])

n = np.diag([1, -1, -1, -1])

In [3]:
def Anticonmutador(i,j):
    A = D[i]
    B = D[j]
    return A@B+B@A

def AlgebraCliff(i,j):
    return 2*n[i][j]*np.identity(4)

In [4]:
A = AlgebraCliff(1,2)
print(A)
B = Anticonmutador(1,2)
print(B)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [5]:
A = AlgebraCliff(0,0)
print(A)
B = Anticonmutador(0,0)
print(B)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
[[2.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 2.+0.j]]


In [6]:
A = AlgebraCliff(1,1)
print(A)
B = Anticonmutador(1,1)
print(B)

[[-2. -0. -0. -0.]
 [-0. -2. -0. -0.]
 [-0. -0. -2. -0.]
 [-0. -0. -0. -2.]]
[[-2.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -2.+0.j]]


In [7]:
A = AlgebraCliff(2,2)
print(A)
B = Anticonmutador(2,2)
print(B)

[[-2. -0. -0. -0.]
 [-0. -2. -0. -0.]
 [-0. -0. -2. -0.]
 [-0. -0. -0. -2.]]
[[-2.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -2.+0.j]]


In [8]:
A = AlgebraCliff(3,3)
print(A)
B = Anticonmutador(3,3)
print(B)

[[-2. -0. -0. -0.]
 [-0. -2. -0. -0.]
 [-0. -0. -2. -0.]
 [-0. -0. -0. -2.]]
[[-2.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -2.+0.j]]


Para todos los ejemplos anteriores se puede ver que aplicar la definicion directa del anticonmutador es igual a utilizar el metodo del algebra de Clifford. Ademas, se puede ver que el anticonmutador es igual a 0 siempre que $$\mu \neq \nu$$ . 
