In [ ]:
import numpy as np

In [ ]:
def Gauss_Seidel(A,b,x0, itmax=1000, tolerancia= 1e-9):
    
    x = x0.copy()
    
    for it in range(itmax):
        
       
        
        for i in range(A.shape[0]):
            
            sum_ = 0.
            for j in range(A.shape[1]):
                if j!=i:
                  sum_ += A[i,j]*x[j]     
            x[i] = (b[i] - sum_)/A[i,i]  
            

            
        residuo = np.linalg.norm( np.dot(A,x) - b )
        
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    return x

In [ ]:
def matrix_triangular_division(A):
  N = len(A)
  L = np.zeros((N,N))
  U = np.zeros((N,N))
  U[0] = A[0]
  x0 = np.zeros(N)
  C = A.copy()
  for j in range(N):
    for i in range(N):
      if i == j:
        L[i][j] = 1
      
      if i > j and j == 0:
        L[i][j] = A[i][j]/U[0][0]
      if i > j:
        C[i][j] = 0
           
  for i in range(N):
    for j in range(N):
        if i > j and j != 0:
          sol = (A[i][j]-(L[i][j-1]*U[j-1][i-1]))/U[j][i-1]
          L[i][j] = sol
    B = Gauss_Seidel(L,A[:,i],x0)
    U[:,i] = B
    for j in range(N):
       if i > j:
         U[i][j] = 0

      
  return L,U

In [ ]:
A = np.array([[4,-2,1],[20,-7,12],[-8,13,17]])
sol = matrix_triangular_division(A)

In [ ]:
print(sol[0])
print(sol[1])

[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]
