In [1]:
import numpy as np

In [2]:
Jx = np.array([[0, 0, 0], [0, 0,-1], [0, 1,0]])
Jy = np.array([[0, 0, 1], [0, 0,0], [-1, 0,0]])
Jz = np.array([[0, -1, 0], [1, 0,0], [0, 0,0]])

J = (Jx,Jy,Jz)

In [9]:
Jx

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [ 0,  1,  0]])

In [4]:
Jy

array([[ 0,  0,  1],
       [ 0,  0,  0],
       [-1,  0,  0]])

In [5]:
Jz

array([[ 0, -1,  0],
       [ 1,  0,  0],
       [ 0,  0,  0]])

In [22]:
def conmutador(i,j):
    A = J[i-1]
    B = J[j-1]
    return A@B-B@A

def TensorLeviChivita(permutacion):
    e = 0
    if (permutacion == [1,2,3]) or (permutacion == [2,3,1]) or (permutacion == [3,1,2]):
        e = 1
    elif (permutacion == [3,2,1]) or (permutacion == [1,3,2]) or (permutacion == [2,1,3]):
        e = -1
    return e

def AlgebraLie(A,B):
    indices = [1,2,3]
    
    if A != B:
        indices.remove(A)
        indices.remove(B)
        
    e = TensorLeviChivita([A,B,indices[0]])
    
    return e*J[indices[-1]-1]
     

Permutacion par:

De acuerdo con la teoria, al calcular un conmutador de dos operadores (matrices) el resultado de estos puede ser expresado mediante el algebra de Lie de la siguiente forma:


[$J_i, J_j$] = $\epsilon_{ijk} J_k$, con  i, j, k = x, y, z

al realizar una permutacion par, es decir de la forma (x,y,z), (y,z,x),(z,x,y), el tensor de Levi-Civita es 1. <br>
al realizar una permutacion impar, es decir de la forma (z,y,x), (x,z,y),(y,x,z), el tensor de Levi-Civita es -1. <br>
o 0 si i = j, j = k o k=1 <br>

Lo anterior se prueba a continuacion

In [23]:
A = AlgebraLie(1,2)
print(A)
B = conmutador(1,2)
print(B)

[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]


In [27]:
A = AlgebraLie(2,1)
print(A)
B = conmutador(2,1)
print(B)

[[ 0  1  0]
 [-1  0  0]
 [ 0  0  0]]
[[ 0  1  0]
 [-1  0  0]
 [ 0  0  0]]


In [28]:
A = AlgebraLie(1,1)
print(A)
B =conmutador(1,1)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
A = AlgebraLie(3,1)
print(A)
B = conmutador(3,1)
print(B)

[[ 0  0  1]
 [ 0  0  0]
 [-1  0  0]]
[[ 0  0  1]
 [ 0  0  0]
 [-1  0  0]]


Para todos los ejemplos anteriores se puede ver que aplicar la definicion directa del conmutador es igual a utilizar el metodo del algebre de Lie. Una observacion adicional es que [A,B] = -[B,A]
