In [ ]:
import numpy as np

In [ ]:
def matrix_multiplication(A,B):
  N_1 = len(A)
  M_1 = len(A[0])
  M_2 = len(B[0])
  C = np.zeros((N_1,M_2))
  for i in range (N_1):
    for j in range(M_2):
      contador = 0
      for k in range(M_1):
        contador += A[i][k]*B[k][j]
      C[i][j] = contador


  return C

In [ ]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,2,-1],[0,3,7],[0,0,2]])
print(A)
print(B)

[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
[[ 4  2 -1]
 [ 0  3  7]
 [ 0  0  2]]


In [ ]:
matrix_multiplication(A,B)

array([[ 4.,  2., -1.],
       [20., 13.,  2.],
       [-8.,  5., 25.]])