In [2]:
import numpy as np
import sympy as sym

In [3]:
def PolLaguerre(grado):
    
    n = sym.Symbol('n',real=True)
    x = sym.Symbol('x',real=True)
    
    f1 = sym.exp(-x)*(x**n)
    f1 = sym.diff(f1.subs(n, grado), x, grado)
    f = (sym.exp(x)/(sym.factorial(n))*f1)
    
    F = f.subs(n, grado)   
    return F

In [4]:
def Derivative(f,x,h=1e-4):
    return (f(x+h)-f(x-h))/(2*h)

In [5]:
def GetNewtonRaphson(f,df,xn,itmax = 100, precision=1e-10):
    
    error = 1
    it = 0
    
    while error > precision and it <= itmax:
        
        try:          
            xn1 = xn - f(xn)/df(f,xn)
            
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            
            return "Not Found"
            
        it += 1
        xn = xn1
    
    if it == itmax:
        False
    else:
        return xn

In [6]:
def GetAllRoots(f, df, Newton_Raphson, n, h=0.1, tolerancia=6):
    
    Roots = np.array([])
    
    encontradas = 0
    ubicacion = 0
    
    while encontradas < n:
        
        xn_1 = ubicacion + h
        xn = ubicacion
        
        
        dn_1 = df(f, xn_1)
        dn = df(f, xn)

            
        if (f(xn) * f(xn_1)  <= 0.) or (dn * dn_1 <= 0.):
            cero = Newton_Raphson(f, df, xn_1)
            if cero != "Not Found":
                rcero = np.round(cero, tolerancia)
            
                iguales = False
            
                for root in Roots:
                    d = np.abs(root - rcero)
                    if d < 1e-5:
                        iguales = True
            
                if not iguales and rcero not in Roots:
                    Roots = np.append(Roots, rcero)
                    encontradas += 1
        
        ubicacion += h
        
        if ubicacion > 100.:
            print("Mayor a 100")
            return Roots
    
    Roots.sort()
    
    return Roots

In [7]:
def Encontrarraices(n):
    x = sym.Symbol('x',real=True)
    
    Roots = []
    
    for i in range(1, n+1):
        f = PolLaguerre(i)
        f = sym.lambdify([x], f, 'numpy')
        roots = GetAllRoots(f, Derivative, GetNewtonRaphson, i)
        
        Roots.append(roots)
        
    return Roots

In [8]:
AllRoots = Encontrarraices(20)

In [10]:
for Roots in AllRoots:
    print("Raices del polinomio grado " + str(len(Roots)) + ":")
    print(Roots,"\n")

Raices del polinomio grado 1:
[1.] 

Raices del polinomio grado 2:
[0.585786 3.414214] 

Raices del polinomio grado 3:
[0.415775 2.29428  6.289945] 

Raices del polinomio grado 4:
[0.322548 1.745761 4.53662  9.395071] 

Raices del polinomio grado 5:
[ 0.26356   1.413403  3.596426  7.08581  12.640801] 

Raices del polinomio grado 6:
[ 0.222847  1.188932  2.992736  5.775144  9.837467 15.982874] 

Raices del polinomio grado 7:
[ 0.193044  1.026665  2.567877  4.900353  8.182153 12.73418  19.395728] 

Raices del polinomio grado 8:
[ 0.17028   0.903702  2.251087  4.2667    7.045905 10.758516 15.740679
 22.863132] 

Raices del polinomio grado 9:
[ 0.152322  0.80722   2.005135  3.783474  6.204957  9.372985 13.466237
 18.833598 26.374072] 

Raices del polinomio grado 10:
[ 0.137793  0.729455  1.808343  3.401434  5.552496  8.330153 11.843786
 16.279258 21.996586 29.920697] 

Raices del polinomio grado 11:
[ 0.125796  0.665418  1.647151  3.091138  5.029284  7.509888 10.605951
 14.431614 19.178857